version: '3.8'

services:
  ms-clients:
    build: ./svc-clients
    container_name: ms-clients
    restart: unless-stopped
    env_file:
      - ./svc-clients/.env
    ports:
      - "8001:8000"

  ms-vehicles:
    build: ./svc-vehicles
    container_name: ms-vehicles
    restart: unless-stopped
    env_file:
      - ./svc-vehicles/.env
    ports:
      - "8002:8080"

  ms-shipments:
    build: ./svc-shipments
    container_name: ms-shipments
    restart: unless-stopped
    env_file:
      - ./svc-shipments/.env
    ports:
      - "8003:3000"

  ms-tracking:
    build: ./svc-tracking
    container_name: ms-tracking
    restart: unless-stopped
    env_file:
      - ./svc-tracking/.env
    ports:
      - "8004:8000"

  ms-analytics:
    build: ./svc-analytics
    container_name: ms-analytics
    restart: unless-stopped
    env_file:
      - ./svc-analytics/.env
    ports:
      - "8005:8000"
